// This file is generated automatically by extractStrings.js
// Do not edit this file manually

export type Strings =
  | "json"
  | "homeLink"
  | "galleryLink"
  | "bookingLink"
  | "reviewsLink"
  | "directionsLink"
  | "FRFlagAlt"
  | "ENFlagAlt"
  | "pageTitle"
  | "pageDescription"
  | "title"
  | "subtitle"
  | "booking";
